version: '2'
services:
  node:
    build: ./node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/src
      - /src/node_modules
    links:
     - mongo
    command: nodemon --legacy-watch /src/bin/www
    environment:
      - NODE_ENV=development
      # - NODE_ENV=production

  mongo:
    image: mongo

  mongo-express:
    image: mongo-express
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8081:8081"